package:
  name: chemlab
  version: 0.4.1

source:
  path: ../../

requirements:
  build:
    - python 3.4*
    - setuptools
    - cython
    - numpy
    - mingwpy

  run:
    - python 3.4*
    - ipython-notebook
    - numpy
    - scipy
    - pyqt
    - pyopengl
    - cclib # No Python3
    - chemview
    - cython
    - six

test:
  imports:
    - chemlab
    - chemlab.io
    - chemlab.db
    - chemlab.core

about:
  home: http://chemlab.rtfd.org
  license: GNU General Public License v3 (GPLv3)
  summary: The Python Computational Chemistry library you were waiting for.
